# Generated by Django 4.2a1 on 2023-01-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='movie',
        ),
    ]
